package com.cadentia.asset;

public enum AssetUploadErrorCode {
    UPLOAD_NOT_FOUND,
    UPLOAD_ALREADY_COMPLETED,
    UNAUTHORIZED_ACTOR,
    INSTANCE_SCOPE_MISMATCH,
    EXPIRED_UPLOAD,
    STORAGE_KEY_MISMATCH,
    OBJECT_NOT_FOUND,
    CHECKSUM_MISMATCH,
    BYTE_SIZE_MISMATCH,
    MIME_TYPE_MISMATCH,
    MIME_TYPE_NOT_ALLOWED,
    OBJECT_TOO_LARGE,
    ASSET_TYPE_MISMATCH,
    STORAGE_FAILURE
}
