package com.cadentia.songimport;

public enum ConnectorErrorCode {
    POLICY_BLOCKED,
    INVALID_CONFIGURATION,
    AUTHENTICATION_FAILED,
    RATE_LIMITED,
    SOURCE_UNAVAILABLE,
    UNSUPPORTED_PAYLOAD,
    PARSE_FAILED,
    NORMALIZATION_FAILED,
    VALIDATION_FAILED,
    STAGING_FAILED,
    UNKNOWN
}
