import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const repoRoot = resolve(import.meta.dirname, '../../..');
const openApiEntrypoint = resolve(repoRoot, 'apps/api/src/main/openapi/cadentia-api.yaml');
const outputPath = resolve(repoRoot, 'apps/admin-web/src/generated/cadentia-api/routes.ts');
const readmePath = resolve(repoRoot, 'apps/admin-web/src/generated/cadentia-api/README.md');
const checkOnly = process.argv.includes('--check');

const spec = readFileSync(openApiEntrypoint, 'utf8');
const pathMatches = [...spec.matchAll(/^  "([^"]+)":\n    "\$ref": "([^"]+)"/gm)];
if (pathMatches.length === 0) {
    console.error(`No documented paths found in ${openApiEntrypoint}`);
    process.exit(1);
}

const operationMethods = ['get', 'post', 'put', 'patch', 'delete'];

const pointerToPathKey = (ref) => {
    const pointer = ref.split('#/')[1] ?? '';
    return pointer
        .split('/')
        .map((part) => part.replaceAll('~1', '/').replaceAll('~0', '~'))
        .join('/');
};

const operationBlocks = (ref) => {
    const [relativePath] = ref.split('#/');
    const pathFile = resolve(dirname(openApiEntrypoint), relativePath);
    const pathKey = pointerToPathKey(ref);
    const lines = readFileSync(pathFile, 'utf8').split(/\r?\n/);
    const pathStart = lines.findIndex((line) => line === `"${pathKey}":`);
    if (pathStart < 0) {
        throw new Error(`Could not resolve ${ref} in ${pathFile}`);
    }

    const pathLines = [];
    for (let index = pathStart + 1; index < lines.length; index += 1) {
        if (lines[index].startsWith('"')) break;
        pathLines.push(lines[index]);
    }

    return operationMethods.flatMap((method) => {
        const methodStart = pathLines.findIndex((line) => line === `  ${method}:`);
        if (methodStart < 0) return [];
        const methodLines = [];
        for (let index = methodStart + 1; index < pathLines.length; index += 1) {
            if (operationMethods.some((candidate) => pathLines[index] === `  ${candidate}:`)) break;
            methodLines.push(pathLines[index]);
        }
        const operationIdLine = methodLines.find((line) => line.trim().startsWith('operationId:'));
        const operationId = operationIdLine?.split(':').slice(1).join(':').trim();
        if (!operationId) {
            throw new Error(`Missing operationId for ${method.toUpperCase()} ${pathKey}`);
        }
        return [{ method: method.toUpperCase(), operationId }];
    });
};

const routes = pathMatches.map(([, path, ref]) => ({
    path,
    ref,
    operations: operationBlocks(ref),
})).sort((a, b) => a.path.localeCompare(b.path));
const operations = routes.flatMap((route) => route.operations.map((operation) => ({
    path: route.path,
    ref: route.ref,
    ...operation,
}))).sort((a, b) => a.operationId.localeCompare(b.operationId));
const duplicateOperationIds = operations
    .map((operation) => operation.operationId)
    .filter((operationId, index, operationIds) => operationIds.indexOf(operationId) !== index);
if (duplicateOperationIds.length > 0) {
    console.error(`Duplicate operationIds found: ${[...new Set(duplicateOperationIds)].join(', ')}`);
    process.exit(1);
}
const highRiskRoutes = routes.filter((route) => route.path.includes('rollback') || route.path.includes('feature-flags'));
const destructiveWithoutPreview = highRiskRoutes.filter((route) => route.path.endsWith(':confirm') && !routes.some((candidate) => candidate.path === route.path.replace(':confirm', ':preview')));
if (destructiveWithoutPreview.length > 0) {
    console.error(`High-risk confirmation routes missing preview companions: ${destructiveWithoutPreview.map((route) => route.path).join(', ')}`);
    process.exit(1);
}

const generated = `// Generated by apps/admin-web/scripts/generate-client.mjs from apps/api/src/main/openapi/cadentia-api.yaml.\n// Do not edit by hand.\n\nexport type CadentiaApiRoute =\n${routes.map((route) => `    | '${route.path}'`).join('\n')};\n\nexport type CadentiaApiOperationId =\n${operations.map((operation) => `    | '${operation.operationId}'`).join('\n')};\n\nexport type CadentiaApiMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST' | 'PUT';\n\nexport type CadentiaApiOperation = {\n    operationId: CadentiaApiOperationId;\n    method: CadentiaApiMethod;\n    path: CadentiaApiRoute;\n    ref: string;\n};\n\nexport const cadentiaApiRoutes = [\n${routes.map((route) => `    '${route.path}',`).join('\n')}\n] as const satisfies readonly CadentiaApiRoute[];\n\nexport const cadentiaApiRouteRefs: Record<CadentiaApiRoute, string> = {\n${routes.map((route) => `    '${route.path}': '${route.ref}',`).join('\n')}\n};\n\nexport const cadentiaApiOperations = [\n${operations.map((operation) => `    { operationId: '${operation.operationId}', method: '${operation.method}', path: '${operation.path}', ref: '${operation.ref}' },`).join('\n')}\n] as const satisfies readonly CadentiaApiOperation[];\n\nexport const cadentiaApiOperationsById = Object.fromEntries(\n    cadentiaApiOperations.map((operation) => [operation.operationId, operation]),\n) as Record<CadentiaApiOperationId, CadentiaApiOperation>;\n`;
const readme = `# Generated Cadentia API client\n\nThis directory is generated from \`apps/api/src/main/openapi/cadentia-api.yaml\`.\n\nRun \`npm run generate:client -w @cadentia/admin-web\` after OpenAPI changes.\nCI should run \`npm run generate:client:check -w @cadentia/admin-web\` to fail when artifacts drift.\nDo not hand-author runtime calls against undocumented endpoints in this directory.\n`;

function verify(path, expected) {
    let actual = '';
    try {
        actual = readFileSync(path, 'utf8');
    } catch {
        actual = '';
    }
    if (actual !== expected) {
        console.error(`Generated artifact is stale: ${path}`);
        return false;
    }
    return true;
}

if (checkOnly) {
    const ok = verify(outputPath, generated) && verify(readmePath, readme);
    process.exit(ok ? 0 : 1);
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, generated);
writeFileSync(readmePath, readme);
console.log(`Generated ${routes.length} documented API routes.`);
