import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const repoRoot = resolve(import.meta.dirname, '../../..');
const openApiEntrypoint = resolve(repoRoot, 'apps/api/src/main/openapi/cadentia-api.yaml');
const outputPath = resolve(repoRoot, 'apps/admin-web/src/generated/cadentia-api/routes.ts');
const readmePath = resolve(repoRoot, 'apps/admin-web/src/generated/cadentia-api/README.md');
const checkOnly = process.argv.includes('--check');

const spec = readFileSync(openApiEntrypoint, 'utf8');
const pathMatches = [...spec.matchAll(/^  "([^"]+)":\n    "\$ref": "([^"]+)"/gm)];
if (pathMatches.length === 0) {
    console.error(`No documented paths found in ${openApiEntrypoint}`);
    process.exit(1);
}

const routes = pathMatches.map(([, path, ref]) => ({ path, ref })).sort((a, b) => a.path.localeCompare(b.path));
const highRiskRoutes = routes.filter((route) => route.path.includes('rollback') || route.path.includes('feature-flags'));
const destructiveWithoutPreview = highRiskRoutes.filter((route) => route.path.endsWith(':confirm') && !routes.some((candidate) => candidate.path === route.path.replace(':confirm', ':preview')));
if (destructiveWithoutPreview.length > 0) {
    console.error(`High-risk confirmation routes missing preview companions: ${destructiveWithoutPreview.map((route) => route.path).join(', ')}`);
    process.exit(1);
}

const generated = `// Generated by apps/admin-web/scripts/generate-client.mjs from apps/api/src/main/openapi/cadentia-api.yaml.\n// Do not edit by hand.\n\nexport type CadentiaApiRoute =\n${routes.map((route) => `    | '${route.path}'`).join('\n')};\n\nexport const cadentiaApiRoutes = [\n${routes.map((route) => `    '${route.path}',`).join('\n')}\n] as const satisfies readonly CadentiaApiRoute[];\n\nexport const cadentiaApiRouteRefs: Record<CadentiaApiRoute, string> = {\n${routes.map((route) => `    '${route.path}': '${route.ref}',`).join('\n')}\n};\n`;
const readme = `# Generated Cadentia API client\n\nThis directory is generated from \`apps/api/src/main/openapi/cadentia-api.yaml\`.\n\nRun \`npm run generate:client -w @cadentia/admin-web\` after OpenAPI changes.\nCI should run \`npm run generate:client:check -w @cadentia/admin-web\` to fail when artifacts drift.\nDo not hand-author runtime calls against undocumented endpoints in this directory.\n`;

function verify(path, expected) {
    let actual = '';
    try {
        actual = readFileSync(path, 'utf8');
    } catch {
        actual = '';
    }
    if (actual !== expected) {
        console.error(`Generated artifact is stale: ${path}`);
        return false;
    }
    return true;
}

if (checkOnly) {
    const ok = verify(outputPath, generated) && verify(readmePath, readme);
    process.exit(ok ? 0 : 1);
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, generated);
writeFileSync(readmePath, readme);
console.log(`Generated ${routes.length} documented API routes.`);
