package com.cadentia.reng.scoring;

public enum HardFilterReasonCode {
    EXCLUDED_BY_USER,
    MISSING_PROVENANCE,
    MISSING_APPROVAL_SUMMARY,
    FAILED_APPROVAL_GATE,
    UNSUPPORTED_LANGUAGE,
    MISSING_KEY,
    MISSING_TEMPO,
    TEAM_MISSING_REQUIRED_INSTRUMENT,
    TEAM_INSUFFICIENT_SKILL_COVERAGE,
    TEAM_LEAD_VOCAL_RANGE_MISMATCH,
    TEAM_MISSING_VOCAL_CONFIGURATION,
    TEAM_UNAVAILABLE_ASSIGNED_MUSICIAN,
    TEAM_INCOMPLETE
}
