package com.cadentia.reng.scoring;

public enum TeamConstraintCode {
    MISSING_REQUIRED_INSTRUMENT,
    INSUFFICIENT_SKILL_COVERAGE,
    LEAD_VOCAL_RANGE_MISMATCH,
    MISSING_VOCAL_CONFIGURATION,
    UNAVAILABLE_ASSIGNED_MUSICIAN,
    OPTIONAL_INSTRUMENT_FIT,
    INCOMPLETE_TEAM
}
